name: chunked_downloader
description: A dart package to download files with custom chunk sizes for faster downloads.
version: 1.1.0
homepage: https://github.com/bostrot/chunked_downloader

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  http: ^1.6.0
  async: ^2.13.1

dev_dependencies:
  test: ^1.27.0
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
