name: chunked_downloader
description: A dart package to download files with custom chunk sizes for faster downloads.
version: 1.0.0
homepage: https://github.com/bostrot/chunked_downloader

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  http: ^0.13.3
  async: ^2.9.0

dev_dependencies:
  test: ^1.16.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
